Repository TravelWithMeProject/GoWithMe_Front, pull requests merged in 2022-01, with the labels that each got.

#2 [Test] Test
  app/src/pages/index.tsx
Labels: documentation

#3 [develop] pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  TEMPLATE.md
  app/src/components/ChildNesting/index.tsx
  app/src/components/Nav/index.tsx
  app/src/components/Nav/style.ts
  app/src/components/ParentNesting/index.tsx
  app/src/components/ParentNesting/style.ts
  app/src/pages/ChildNesting/index.tsx
  app/src/pages/Home/index.tsx
  app/src/pages/ParentNesting/index.tsx
  app/src/pages/index.tsx
  app/src/pages/router.tsx
Labels: documentation

#8 [route] Route Setting
  app/src/pages/Community/index.tsx
  app/src/pages/Travel/index.tsx
  app/src/pages/User/index.tsx
  app/src/pages/index.tsx
  app/src/pages/router.tsx
Labels: Feature, Setting

#11 [storybook] Storybook Example
  app/src/components/StoryBookExample/index.tsx
  app/src/pages/Community/index.tsx
  app/src/pages/Travel/index.tsx
  app/src/pages/User/index.tsx
  app/src/pages/index.tsx
  app/src/pages/router.tsx
  app/src/stories/Components/Example.stories.tsx
Labels: Feature, Setting

#13 [Button]: Create Button Component
  app/src/components/Button/index.tsx
  app/src/components/Button/style.tsx
  app/src/components/StoryBookExample/index.tsx
  app/src/stories/Components/Button.stories.tsx
  app/src/stories/Components/Example.stories.tsx
Labels: Feature

#15 [contentBar] Create ContentBar Component
  app/src/components/ContentBar/index.tsx
  app/src/components/ContentBar/style.tsx
  app/src/stories/Components/ContentBar.stories.tsx
Labels: Feature

#18 [button]: modify type of width
  app/src/components/Button/index.tsx
  app/src/components/Button/style.tsx
  app/src/stories/Components/Button.stories.tsx
Labels: Fix

#20 [header] Header
  app/src/components/Header/index.tsx
  app/src/components/Header/style.tsx
  app/src/components/StoryBookExample/index.tsx
  app/src/pages/index.tsx
  app/src/stories/Components/Example.stories.tsx
  app/src/stories/Components/Header.stories.tsx
Labels: Feature, Style

#21 [button] change existing props into suitable props
  app/src/components/Button/index.tsx
  app/src/components/Button/style.tsx
  app/src/stories/Components/Button.stories.tsx
Labels: Fix

#22 [header] Header
  app/src/pages/index.tsx
Labels: Fix

#24 [storybook] Storybook Router Setting
  app/.storybook/preview.js
  app/src/stories/Components/Header.stories.tsx
Labels: Setting

#29 [materials] 준비물 체크리스트
  app/src/components/ContentBar/index.tsx
  app/src/components/ContentBar/style.tsx
  app/src/components/TravelPlan/Materials/index.tsx
  app/src/components/TravelPlan/Materials/style.tsx
  app/src/stories/Components/TravelPlan/Mateirals.stories.tsx
Labels: Feature

#33 [mainLayout] 레이아웃 제작
  app/src/components/Common/index.tsx
  app/src/components/MainLayout/LoginSection/index.tsx
  app/src/components/MainLayout/LoginSection/styled.tsx
  app/src/components/MainLayout/MainSection/index.tsx
  app/src/components/MainLayout/MainSection/style.tsx
  app/src/stories/Components/LoginLayout.stories.tsx
  app/src/stories/Components/MainLayout.stories.tsx
Labels: Feature

#44 [travelPlanHeader] 여행 플랜 헤더 제작
  app/src/components/TravelPlan/Header/index.tsx
  app/src/components/TravelPlan/Header/styles.tsx
  app/src/static/assets/arrow-icon-right.svg
  app/src/stories/Components/TravelPlan/Mateirals.stories.tsx
  app/src/stories/Components/TravelPlan/TravelPlanHeader.stories.tsx
Labels: Feature

#42 [companion] 동행자
  1
  app/src/components/TravelPlan/Companion/index.tsx
  app/src/components/TravelPlan/Companion/style.tsx
  app/src/stories/Components/TravelPlan/Companion.stories.tsx
Labels: Feature

#46 [route] 라우트 추가
  1
  app/src/components/TravelPlan/Memo/index.tsx
  app/src/pages/Community/index.tsx
  app/src/pages/FindId/index.tsx
  app/src/pages/FindPassword/index.tsx
  app/src/pages/Home/index.tsx
  app/src/pages/Travel/index.tsx
  app/src/pages/TravelPlan/index.tsx
  app/src/pages/User/index.tsx
  app/src/pages/index.tsx
  app/src/pages/router.tsx
  app/src/stories/Components/TravelPlan/Companion.stories.tsx
  app/src/stories/Components/TravelPlan/Memo.stories.tsx
Labels: Feature
